name: finflow
description: A Flutter base project for the FinFlow personal finance mobile app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  fl_chart: 0.70.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^22.2.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.3.0
  flutter_timezone: ^5.1.0
  http: ^1.6.0
  image_picker: ^1.2.2
  path: ^1.9.1
  record: ^7.1.1
  shared_preferences: ^2.5.5
  speech_to_text: ^7.4.0
  sqflite: ^2.4.2
  supabase_flutter: ^2.15.0
  timezone: ^0.11.1
  visibility_detector: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/chatbot/
    - assets/icons/home/
    - assets/icons/categories/
    - assets/icons/categories/duotone/
    - assets/icons/categories/fill/
    - assets/logos/banks/
    - assets/logos/ewallets/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
    - family: Hanken Grotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk.ttf
